### ISSUE TITLE
How to view the live stream in HLS format for mobile or No Flash

### ISSUE THREAD

**Issue by omarojo** [red5pro/red5pro-server-examples#1]
I installed the server in my machine and tried the iOS sample app to publish a live stream. I was able to see the live stream listed in the server sample webpage. But the only way to see the stream was using the integrated Flash Player, which doesnt work in mobile web browsers.

How can I view the stream in Mobile Web Browsers (iOS and Android) as well as Desktop Browsers (Safari, Chrome, Firefox) without using a Flash player ? Is there a way to have HLS available for playback ?

**Comment by cameroninfrared5** [comment]
Hi Omar,

Good news, HLS is coming in our next release!
