### ISSUE TITLE
Time Conversion

### ISSUE THREAD

**Issue by Shubham1993** [red5pro/red5pro-server-examples#18]
{
  "status": "success",
  "code": 200,
  "data": {
    "bytes_received": 3584956,
    "active_subscribers": 1,
    "total_subscribers": 3,
    "max_subscribers": 2,
    "id": 1,
    "name": "0e329449-3f8a-4726-b6da-d008ee7240b2",
    "publish_name": "mylifemyattitude___20",
    "creation_time": 1475228847644,
    "scope_path": "/default",
    "is_recording": true,
    "state": "uninit"
  },
  "timestamp": 1475229107399
}

In what time zone or format the creation time and timestamp is shown? I get this data using stream api of red5pro.

**Comment by bustardcelly** [comment]
`timestamp` is generated using `System.currentTimeMillis()`, so it depends on system's timezone setting.

Also the `timestamp` param in response is also local server timezone specific. Its just a additional metadata, nothing more. You can use it to find out delay in between 2 consecutive calls.

**Comment by rajdeeprath** [comment]
The timestamp param in response is also local server timezone specific. That its just an additional metadata  nothing more. It  may be used to find out delay in between 2 consecutive calls or average delay in between multiple calls.

Similarly, the creation_time is also generated with respect to local server time zone. Hope that answers your question!.

**Comment by rajdeeprath** [comment]
The timestamp param in response is  local server timezone specific. That its just an additional metadata nothing more. It may be used to find out delay in between 2 consecutive calls or average delay in between multiple calls. Similarly, the creation_time is also generated with respect to local server time zone.
